Feature/implementation
gherking/gpc-filter pull request #1
Opened 2022-02-13 20:47 UTC by rakur

2022-02-21 07:52 UTC, szikszail requested changes

2022-02-21 07:52 UTC, szikszail commented on README.md
> +Excluding scenarios with @wip tag
Please add the configuration of the example as well, that would demonstrate the usage of cucumber tag expressions.

2022-02-21 07:52 UTC, szikszail commented on src/types.ts
> +    excludeScenarioTags?: Array<string>,
Please use `string[]`, in general in the source files.

2022-02-21 07:52 UTC, szikszail commented on src/types.ts
> +export interface FilterConfig {
In the description of the GPC, you mention the use of cucumber-tag-expressions, but you seem to expect individual tags and not the expression. I'd suggest updating the implementation to use the expression (https://www.npmjs.com/package/cucumber-tag-expressions).

2022-02-21 07:52 UTC, szikszail commented on src/index.ts
> +class Filter implements PreCompiler {
In general, you implemented the filtering logic at the event method level. I think the pre methods would be more suitable for this logic.

2022-02-23 06:48 UTC, szikszail requested changes

2022-02-23 06:48 UTC, szikszail commented on src/index.ts
> +        if (feature.elements.length && feature.elements.some((element: Element) =>
Feature files can be localized, thus relying on the keywords is not suggested. Please use `instanceof`. 

Also:
```javascript
if (condition) {
  return true;
}
return false;
// instead:
return condition;
```

2022-02-23 06:48 UTC, szikszail commented on src/index.ts
> +        if (rule.elements.length && rule.elements.some((element: Element) => element.keyword === "Scenario" || element.keyword === "Scenario Outline")) {
Same as for the `postFeature`

2022-02-23 06:48 UTC, szikszail commented on src/index.ts
> +        for (const example of scenarioOutline.examples) {
You have already evaluated at this point that there is at least one example matching the expression, thus I don't think you need to check example tags, or even checking tags of the scenario outline seems unnecessary at this point.

2022-02-23 06:48 UTC, szikszail commented on README.md
> +| `includeScenarioTags` | `Array` | Scenarios with the given tag will be included in the result | Optional |
Please update this table.

2022-02-23 06:48 UTC, szikszail commented on README.md
> +Excluding scenarios with @wip or @exclude tags
I'd either rephrase it: "Keeping scenarios with `@current` tag", or set a filter what means this condition.

2022-02-26 11:59 UTC, szikszail approved these changes

2022-03-04 19:34 UTC, MonikaLaszlo approved these changes

2022-03-06 07:45 UTC, merged